### PR TITLE
API-23423/ Docserver: Jest nesting cleanup - coverage fix

### PR DESCRIPTION
**Pull request by mheusgit**
- Fix corrects misreported code coverage results due to Jest config being relocated.  Main change of interest is just the addition of "rootDir".  Everything else is just meant to follow this change.
- Added "/fixtures/" as part of coverage ignore

### CODE REVIEW

**Comment by mheusgit** [comment]
Well... that's rather odd.  The DB entry cleaning is taking far too long (over 5 seconds) per integration test.

**Comment by mheusgit** [comment]
@dsteeve @christineyost This PR ran into a interesting problem with our test environment.  Looks like the test DB goes down every so often.

**Review by christineyost — APPROVED** [review]
Works locally for me!

**Comment by mheusgit** [comment]
Some manner of network problem prevented this change from going through standard pipeline.

**Comment by dsteeve** [comment]
do you know what time of day you ran into this db slowness @mheusgit (you can add that info to the ticket)  -- I don't want to hold up this change - so created a ticket for this investigation. https://vajira.max.gov/browse/API-26194

**Pull request merged**
