### PR TITLE
API-21181/  Update docserver loast integration to support a set of suites

### PR DESCRIPTION
**Pull request by mheusgit**
- Updated LOAST data model to include five new fields: suiteId, requestId, error, loastVersion, and requestType
- Included latest release of LOAST to allow suiteId support
- Migration changes include update from Mikro-ORM version bump performed in another ticket
- Fully implemented loastManager.ts logic to avoid ignoring test data
- Resolved bug in loast.service.transactional.ts where LOAST data would be ignored if a setup error was encountered on LOAST's side
- resolveJsonModule added to tsconfig.json to allow reading of module versions (a.k.a. loastVersion)

### CODE REVIEW

**Review by stevelong00 — COMMENTED** [review]
Looks good to me!

**Review by stevelong00 — DISMISSED** [review]
Looks good to me!

**Comment by mheusgit** [comment]
Team decided this PR needs to be in a separate MR from https://github.com/department-of-veterans-affairs/lighthouse-docserver/pull/231

**Comment by mheusgit** [comment]
MR went in for https://github.com/department-of-veterans-affairs/lighthouse-docserver/pull/231.  PR can proceed.

**Review by stevelong00 — APPROVED** [review]
Still looks good

**Pull request merged**
